language: python

notifications:
    email: false

python:
    - "2.7"
    - "3.5"
    - "3.6"

branches:
    only:
        - master
        - dev
install:
    - pip install -r requirements.txt
    - pip install . 

script: 
    - python -c 'import sys; del sys.path[0]; import pyPRISM; pyPRISM.test()'
