language: python

python:
    - "2.7"
    - "3.5"

branches:
    only:
        - master
        - dev
install:
    - pip install -r requirements.txt
    - pip install . 

script: 
    - cd tests
    - pytest --verbose
